export const MINIMAL_HEX_DB = {
  hexes: [
    {
      id: 'Plains_1',
      type: 'Ground',
      terrainTypeId: 1,
      canDestroy: true,
      destroyTransformTo: 'Plains_1',
      destroyTransformToMode: 'HexID',
      destroySources: [],
      canStored: false,
      destroyIncomeEnabled: false,
      destroyIncome: [],
      canBuild: false,
      buildAvailableTiles: [],
      buildMinLevel: 1,
      buildPrice: [],
      buildPremiumPrice: 0,
      buildPlacementRule: '',
      tapIncomeEnabled: true,
      destroyable: true,
      incomeTransformTo: 'Plains_1',
      incomeTransformToMode: 'HexID',
      incomeCapacity: 3,
      incomeGetPerTap: [{ type: 'Gold', amount: 5 }],
      baseCostTaps: 0,
      roadAllowed: true,
    },
  ],
};

export const MINIMAL_BLD_DB = {
  buildings: [
    {
      id: 'TestBuilding_1',
      type: 'Standard',
      textId: '',
      descIdleId: '',
      descBuildId: '',
      spriteName: '',
      biome: 'Any',
      buildingCategory: '',
      canDestroy: true,
      destroyTransformToMode: 'HexID',
      destroyTransformTo: 'Plains_1',
      destroySources: [],
      moveToStorageOnDestroy: false,
      resourceAwardedOnDestroy: false,
      destroyIncome: [],
      canBuild: true,
      needRoad: false,
      availableTiles: [],
      minLevel: 1,
      price: [],
      premiumPrice: 0,
      hexEarnsOnTap: true,
      destroyableByTap: true,
      incomeTransformToMode: 'HexID',
      incomeTransformTo: 'Plains_1',
      capacity: 5,
      getPerTap: [{ type: 'Gold', amount: 10 }],
      incomePerTurn: [],
      incomeConstant: [],
      spendConstant: [],
      stores: [],
      bonuses: [],
    },
  ],
};

/** Minimal 20×20 map so the "New Map" modal does not block interactions. */
export const MINIMAL_MAP = {
  width: 20,
  height: 20,
  data: Array.from({ length: 20 }, () => Array(20).fill('Plain_1')),
  bridges: [],
  settlements: [],
};
